import React, { useState, useEffect, useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../../../../../styles/EditProfileCompany.module.css";
import gStyle from "../../../../../styles/General.module.css";
import SpaceEmpty from "../../../../../components/SpaceEmpty";
import upImg from "../../../../../styles/UploadImg.module.css";
import Router, { useRouter } from "next/router";
import axios from "axios";


Index.layout = "L2";
export default function Index() {
  const [isLoading, setLoading] = useState(false);
  const hiddenFileInput = useRef(null);
  const [avatar, setAvatar] = useState('');

  const [dataUser, setDataUser] = useState([]);
  const router = useRouter();
  const { id } = router.query;
  const [form, setForm] = useState({
    company_recruiter: '',
    business_sector_recruiter: '',
    work_place: '',
    personal_desc: '',
    email: '',
    ig_account: '',
    phone: '',
    linkedin_recruiter: '',
  });

  useEffect(() => {
    setLoading(true)
    axios
      .get(`${process.env.APP_BACKEND_URL}/v1/user/recruiter/show_by_id/${id}`)
      .then((res) => {
        // console.log(res.data.data)

        setDataUser(res.data.data);
        setLoading(false)


      })
      .catch((err) => {
        console.log(err);

      });
  }, [id]);

  const handleClick = (e) => {
    hiddenFileInput.current.click();
  };

  
  // const {query} = useRouter();
  //  console.log(query)

  // const handleImgChange = (e) => {
  //   if(e.target.files && event.target.files[0]) {
  //     const i = event.target.files[0];
  //     const body = new formDataHandler();
  //     body.append("image", i)
  //   }
  // }

  const changeHandle = (e) => {
    const fileUploaded = e.target.files[0];
    document.getElementById('photoBtn').innerHTML = fileUploaded.name;
    setAvatar(fileUploaded)
  }

  const avatarUpdate = (e) => {
    const fileUploaded = e.target.files[0];
    document.getElementById('formFIle').innerHTML = fileUploaded.name;
    setAvatar(fileUploaded);
  }

  

  const avaHandle = (e) => {
    console.log(avatar)
    e.preventDefault();
    let formData = new FormData(e.target)
    formData.append('avatar', avatar);
    postHandle(Object.fromEntries(formData));
  }

  const postHandle = (form) => {
    console.log(avatar);
    console.log(typeof id);
    axios
      .put(`${process.env.APP_BACKEND_URL}/v1/user/update_ava_cloudinary/${id}`, form, {
        headers: {
          'Content-Type': 'multipart/form-data',
        }
      })
      .then((res) => {
        console.log(res);
        alert('Avatar has been updated');
        setAvatar('');
        router.push(`/profile/company_detail/${id}`);
      })
      .catch((err) => {
        console.log(avatar)
        console.log(err);
        alert('failed to update avatar');
    })
    
  }

  


  const handleChange = (e) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value
    })
  }


  const formDataHandler = (e) => {
    e.preventDefault();
    console.log(form)
    const body = {
      company_recruiter: form.company_recruiter,
      business_sector_recruiter: form.business_sector_recruiter,
      work_place: form.work_place,
      personal_desc: form.personal_desc,
      email: form.email,
      ig_account: form.ig_account,
      phone: form.phone,
      linkedin_recruiter: form.linkedin_recruiter,
    };
    console.log(body)
    axios
      .put(`${process.env.APP_BACKEND_URL}/v1/user/update_recruiter_data/${id}`, body)
      .then((res) => {
        console.log(res.data);
        if(res.data.status == 'success') {
          alert('update data recruiter success')
          Router.push(`/profile/company_detail/${id}`)
        } else {
          alert('update data recruiter failed')
        }
        // alert("data update success");
        // router.push(`/profile/company_detail/${id}`);
      })
      .catch((err) => {
        console.log(err);
      });
  }


  return (
    <>
      <Head>
        <title>Edit profile Company - HireJob</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets-img/only logo.png" />
      </Head>
      <SpaceEmpty />
      {
        isLoading ? (
          <>
            loading...
          </>
        ) : (
          <>
            <div className={`position-relative ${styles["kontent-wrapper"]}`}>
              <div className={`${styles["bg-purple"]}`}></div>
              {dataUser.map((item) => (
                <>
                  <div
                    className={`position-absolute ${styles["card-aside-left"]} d-flex `}
                  >
                    <div className="info-wrapper w-100 d-flex flex-column justify-content-center align-items-center">
                      <div
                        className={`${styles["img-wraper"]} pt-5 pb-2  w-100 d-flex justify-content-center align-items-center`}
                      >
                        <Image src={item.ava_url ? (
                          item.ava_url
                        ) : (
                          '/assets-img/ava-default.jpg'
                        )}
                          width={125}
                          height={125}
                          alt="avatar-recruiter"
                          style={{ borderRadius: "50%", paddingTop: "5px", paddingBottom: "2px" }}></Image>
                      </div>
                      <form className="img-edit w-100" onSubmit={avaHandle}>
                        <div className={`${styles["bg-white"]}`}>
                          <div className="mb-5 sect-form-wrapper d-flex gap-2 justify-content-center align-items-center w-100">
                            <div className="edit-icon">
                              <input
                                type="file"
                                id="formFIle"
                                name="avatar"
                                ref={hiddenFileInput}
                                onChange={avatarUpdate}
                              />
                            </div>
                            
                          </div>
                          <div className="ms-3 name-company mb-2 mt-2">
                            <p className={` ${gStyle["open_sans_sb"]} h4`}>
                              {" "}
                              {item.company_recruiter}
                              {" "}
                            </p>
                          </div>
                          <div className="ms-3 job-company">
                            <p className={` ${gStyle["open_sans_sb"]} text-muted`}>
                              {" "}
                              {item.business_sector_recruiter}{" "}
                            </p>
                          </div>
                          <div className="ms-3 location-company d-flex gap-2">
                            <div className="icon-map">
                              <i className="bi bi-geo-alt"></i>
                            </div>
                            <div className="detail-location">
                              <p>{item.work_place}</p>
                            </div>
                          </div>
                          <div className={`${styles["spaceEmpty"]}`}></div>
                        </div>
                        <div className="button-save w-100 d-flex justify-content-center align-items-center mb-2">
                          <button
                            type="submit"
                            className={`btn ${styles["btn-purple"]}`}
                          >
                            Simpan
                          </button>
                        </div>
                        <div className="button-cancel w-100 d-flex justify-content-center align-items-center">
                          <Link href={`/profile/company_detail/${item.user_id}`} className="w-100">
                            <button
                              className={`btn ${styles["btn-white"]}`}
                            >
                              Batal
                            </button>
                          </Link>
                        </div>
                      </form>
                    </div>
                  </div>


                  <div
                    className={`position-absolute ${styles["card-aside-right"]} d-flex flex-column`}
                  >
                    <div
                      className={`company-data-wrapper ${styles["bg-white-pd"]}  w-100 d-flex flex-column mb-3`}
                    >
                      <div className="ms-3 mt-4 title">
                        <p className={`${gStyle["open_sans_sb"]} h4`}>Data Perusahaan</p>
                      </div>
                      <div className={`mt-2 ${styles["line-black"]}`}></div>
                      <div className="form-pd-wrapper">
                        <form
                          className={`mx-3 mt-3`}
                          onSubmit={(e) => formDataHandler(e)}
                        >
                          <div className="mb-3">
                            <label
                              htmlFor="company_name"
                              className={`form-label ${gStyle["open_sans_lt"]}`}
                            >
                              Nama perusahaan
                            </label>
                            <input
                              type="text"
                              className="form-control"
                              id="company_name"
                              name="company_name"
                              aria-describedby="emailHelp"
                              placeholder='Masukkan nama perusahaan'
                              defaultValue={item.company_recruiter}
                              onChange={handleChange}
                            />
                          </div>
                          <div className="mb-3">
                            <label
                              htmlFor="business_sector_recruiter"
                              className={`form-label ${gStyle["open_sans_lt"]}`}
                            >
                              Bidang
                            </label>
                            <input
                              type="text"
                              className="form-control"
                              id="business_sector_recruiter"
                              name="business_sector_recruiter"
                              placeholder='Masukkan bidang perusahaan ex: Financial'
                              defaultValue={item.business_sector_recruiter}
                              // value={item.business_sector_recruiter ? item.business_sector_recruiter : ''}
                              onChange={handleChange}
                            />
                          </div>
                          <div className="mb-3">
                            <label
                              htmlFor="work_place"
                              className={`form-label ${gStyle["open_sans_lt"]}`}
                            >
                              Kota
                            </label>
                            <input
                              type="text"
                              className="form-control"
                              id="work_place"
                              name="work_place"
                              placeholder="Masukkan domisli"
                              defaultValue={item.work_place}
                              onChange={handleChange}
                            />
                          </div>
                          <div className="mb-3">
                            <label
                              htmlFor="personal_desc"
                              className={`form-label ${gStyle["open_sans_lt"]}`}
                            >
                              Deskripsi singkat
                            </label>
                            <textarea
                              className="form-control"
                              id="personal_desc"
                              name="personal_desc"
                              rows="4"
                              placeholder="Tuliskan deskripsi singkat"
                              defaultValue={item.personal_desc}
                              onChange={handleChange}
                            ></textarea>
                          </div>
                          <div className="mb-3">
                            <label
                              htmlFor="email"
                              className={`form-label ${gStyle["open_sans_lt"]}`}
                            >
                              Email
                            </label>
                            <input
                              type="text"
                              className="form-control"
                              id="email"
                              name="email"
                              placeholder="Masukkan email"
                              defaultValue={item.email}
                              onChange={handleChange}
                            />
                          </div>
                          <div className="mb-3">
                            <label
                              htmlFor="ig_account"
                              className={`form-label ${gStyle["open_sans_lt"]}`}
                            >
                              Instagram
                            </label>
                            <input
                              type="text"
                              className="form-control"
                              id="ig_account"
                              name="ig_account"
                              placeholder="Masukkan nama instagram"
                              defaultValue={item.ig_account}
                              onChange={handleChange}
                            />
                          </div>
                          <div className="mb-3">
                            <label
                              htmlFor="phone"
                              className={`form-label ${gStyle["open_sans_lt"]}`}
                            >
                              Nomor Telepon
                            </label>
                            <input
                              type="text"
                              className="form-control"
                              id="phone"
                              name="phone"
                              placeholder="Masukkan nomor telepon"
                              defaultValue={item.phone}
                              onChange={handleChange}
                            />
                          </div>
                          <div className="mb-3">
                            <label
                              htmlFor="linkedin_recruiter"
                              className={`form-label ${gStyle["open_sans_lt"]}`}
                            >
                              Linkedin
                            </label>
                            <input
                              type="text"
                              className="form-control"
                              id="linkedin_recruiter"
                              name="linkedin_recruiter"
                              placeholder="Masukkan nama Linkedin"
                              defaultValue={item.linkedin_recruiter}
                              onChange={handleChange}
                            />
                          </div>
                          <button
                            type="submit"
                            className={`btn ${styles["btn-yellow"]} ${gStyle["open_sans_sb"]} mb-3`}
                          >
                            Simpan
                          </button>
                        </form>
                      </div>
                    </div>
                  </div>
                </>
              ))}
            </div>
          </>
        )

      }

    </>
  );
}
