import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../../../../styles/Companydetail.module.css";
import gStyle from "../../../../styles/General.module.css";
import { useRouter } from "next/router";
import axios from "axios";

export async function getServerSideProps(context) {
  const { id } = context.query;

  try {
    // multiple axios
    const response = await axios({
      method: "GET",
      url: `${process.env.APP_BACKEND_URL}/v1/user/recruiter/show_by_id/${id}`,
    });
    return {
      props: {
        data: response.data.data,
        error: false,
        errorMessage: "",
      },
    };
  } catch (error) {
    return {
      props: {
        data: [],
        dataSkill: [],
        error: true,
        errorMessage: "Error API",
      },
    };
  }
}



const Index = (props) => {
  if(!props) return <div>Loading...</div>
  return (
    <>
      <Head>
        <title>Profile perusahaan - HireJob</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets-img/only logo.png" />
      </Head>

      {
        props.data.map((item, index) => (
          <div key={index} className={`position-relative ${styles["kontent-wrapper"]}`}>

            <div className={`${styles["bg-purple"]}`}></div>
            <div className={`position-absolute ${styles["change-theme"]}`}>
              <div className={`d-flex gap-2`}>
                <div className={`edit-icon`}>
                  <i className="bi bi-pencil"></i>
                </div>
                <div className="desc-text">
                  <p className={`${gStyle["open_sans_sb"]} h5`}>Ubah Latar</p>

                </div>
              </div>
            </div>
            <div
              className={`position-absolute ${styles["card-middle"]} d-flex flex-column justify-content-center align-items-center gap-3`}
            >
              <div className={`${styles["img-wrapper"]}`}>
                <div className={`${styles["img-kontent"]}`}>
                  <Image src={item.ava_url ? (
                    item.ava_url
                  ) : (
                    '/assets-img/ava-default.jpg'
                  )}
                    width={200}
                    height={200}
                    alt="wkwkwk"
                    style={{ borderRadius: "50%" }}></Image>
                </div>
              </div>
              <div className={`company-name`}>
                <p className={`${gStyle["open_sans_sb"]} h4`}>
                  {item.company_recruiter}
                </p>
              </div>
              <div className={`company-spec`}>
                <p className={`${gStyle["open_sans_lt"]} h6 text-muted`}>
                  {item.business_sector_recruiter ? (
                    <>
                      {item.business_sector_recruiter}
                    </>
                  ) : (
                    <>
                      No data business sector recruiter
                    </>
                  )}
                </p>
              </div>
              <div className={`company-location d-flex gap-3`}>
                <div className="location-icon">
                  <i className="bi bi-geo-alt-fill"></i>
                </div>
                <div className="location-desc">
                  <p className={`${gStyle["open_sans_lt"]} h6 text-muted`}>
                    {item.business_sector_recruiter ? (
                      <>
                        {item.work_place}
                      </>
                    ) : (
                      <>
                        No data work place
                      </>
                    )}
                  </p>
                </div>
              </div>
              <div className="company-desc text-center">
                <p className={`${gStyle["open_sans_lt"]} h6 text-muted`}>
                  {item.personal_desc ? (
                    <>
                      {item.personal_desc}
                    </>
                  ) : (
                    <>
                      No data description
                    </>
                  )}
                </p>
              </div>
              <div className="edit-profile-btn w-100 d-flex justify-content-center align-items-center">
                <Link
                  href={`/profile/edit_profile/company/${item.user_id}`}
                  className="w-75 d-flex align-items-center justify-content-center text-decoration-none"
                >
                  <button
                    className={`btn ${styles["btn-purple"]} ${gStyle["open_sans_sb"]}`}
                  >
                    Edit profile
                  </button>
                </Link>
              </div>
              <div className="socmed-wrapper d-flex flex-column">
                <div className="email d-flex gap-2">
                  <div className="icon">
                    <i className="text-muted bi bi-envelope"></i>
                  </div>
                  <div>
                    <p className={`${gStyle["open_sans_lt"]} text-muted`}>
                      {item.email}
                    </p>
                  </div>
                </div>
                <div className="ig d-flex gap-2">
                  <div className="icon">
                    <i className="text-muted bi bi-instagram"></i>
                  </div>
                  <div>
                    <p className={`${gStyle["open_sans_lt"]} text-muted`}>
                      {item.ig_account ? (
                        <>
                          {item.ig_account}
                        </>
                      ) : (
                        <>
                          No data instagram
                        </>
                      )}
                    </p>
                  </div>
                </div>
                <div className="phone d-flex gap-2">
                  <div className="icon">
                    <i className="text-muted bi bi-telephone"></i>
                  </div>
                  <div>
                    <p className={`${gStyle["open_sans_lt"]} text-muted`}>
                      {item.phone ? (
                        <>
                          {item.phone}
                        </>
                      ) : (
                        <>
                          No data phone
                        </>
                      )}
                    </p>
                  </div>
                </div>
                <div className="linkedin d-flex gap-2">
                  <div className="icon">
                    <i className=" text-muted bi bi-linkedin"></i>
                  </div>
                  <div>
                    <p className={`${gStyle["open_sans_lt"]} text-muted`}>
                      {item.linkedin_recruiter ? (
                        <>
                          {item.linkedin_recruiter}
                        </>
                      ) : (
                        <>
                         No Data Linkedin
                        </>
                      )}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        ))
      }

    </>
  );
}

// jika di component ada get data simpan Index.layout sebelum export 
Index.layout = "L2";
export default Index;

