import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../../../../styles/Portofolio.module.css";
import gStyle from "../../../../styles/General.module.css";
import { WorkExp, Portofolio } from "../../../../components/ProfileSect.jsx";
import { useRouter } from "next/router";
import axios from "axios";

export async function getServerSideProps(context) {
  const { id } = context.query;

  try {
    // multiple axios
    const response = await axios({
      method: "GET",
      url: `${process.env.APP_BACKEND_URL}/v1/user/worker/show_by_id/${id}`,
    });
    const responseSkill = await axios({
      method: "GET",
      url: `${process.env.APP_BACKEND_URL}/v1/skill/show_by_user_id/${id}`,
    });

    console.log(responseSkill.data.data);
    return {
      props: {
        data: response.data.data,
        dataSkill: responseSkill.data.data,
        error: false,
        errorMessage: "",
      },
    };
  } catch (error) {
    return {
      props: {
        data: [],
        dataSkill: [],
        error: true,
        errorMessage: "Error API",
      },
    };
  }
}

const Index = (props) => {
  const router = useRouter();
  const { id } = router.query;
  const [idLocal,setIdLocal] = useState();
  useEffect(() => {
    const dataLocal = JSON.parse(localStorage.getItem("data"));
    // console.log(dataLocal)
    setIdLocal(dataLocal.user_id);
    // console.log(idLocal)
  }, []);
  const [showPortofolio, setShowPortofolio] = useState(true);

  const [showWorkExp, setShowWorkExp] = useState(false);

  const onPortofolio = () => {
    setShowPortofolio(true);
    setShowWorkExp(false);
  };

  const onWorkExp = () => {
    setShowPortofolio(false);
    setShowWorkExp(true);
  };
  if (!props) return <div>Loading...</div>;
  // console.log(props.dataSkill.length)
  return (
    <>
      <Head>
        <title>Profile portofolio - HireJob</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      {/* {
                props.dataSkill
            } */}

      {props.data.map((item, index) => (
        <div
          key={index}
          className={`position-relative ${styles["kontent-wrapper"]}`}
        >
          <div className={`${styles["bg-purple"]}`}></div>
          <div className={`position-absolute ${styles["card-aside"]}`}>
            <div
              className={` ${styles["img-wrapper"]} d-flex flex-column justify-content-center align-items-center  col-12`}
            >
              <div className={` ${styles["img-card"]}`}>
                <Image
                  src={
                    item.ava_url ? item.ava_url : "/assets-img/ava-default.jpg"
                  }
                  style={{ borderRadius: "50%" }}
                  width={150}
                  height={150}
                  alt="avatar of worker"
                  priority
                ></Image>
              </div>
            </div>
            <div className={`${styles["info-wrapper"]} d-flex flex-column`}>
              <div className="ms-3 mb-1 name-info ">
                <p className={`${gStyle["open_sans_sb"]} h4`}>
                  {item.full_name}
                </p>
              </div>
              <div className="ms-3 job-spec">
                <p className={`${gStyle["open_sans_lt"]}`}>
                  {item.job_spec ? item.job_spec : <>No data job spec</>}
                </p>
              </div>
              <div className="ms-3 location-info d-flex gap-2">
                <div className="map-icon">
                  <i className="text-muted  bi bi-geo-alt"></i>
                </div>
                <div className="desc-location">
                  <p className={`text-muted  ${gStyle["open_sans_lt"]}`}>
                    {item.domisli ? item.domisli : <>No data domisli</>}
                  </p>
                </div>
              </div>
              <div className={`ms-3 job-type`}>
                <p className={`text-muted  ${gStyle["open_sans_lt"]}`}>
                  {item.job_type ? item.job_type : <>No data job type</>}
                </p>
              </div>
              <div className="ms-3 desc-person w-75">
                <p className={`text-muted  ${gStyle["open_sans_lt"]}`}>
                  {item.personal_desc ? (
                    item.personal_desc
                  ) : (
                    <>No data personal desc</>
                  )}
                </p>
              </div>
              <div className="ms-3 mb-5 hire-btn d-flex w-75">
                <button
                  type="button"
                  className={`btn ${styles["btn-purple"]} w-100`}
                >
                  <p className={`${gStyle["open_sans_sb"]}`}>Hire</p>
                </button>
              </div>
              <div className="ms-3 mb-5 hire-btn d-flex w-75">
                {idLocal == id ? (
                  <>
                    <Link
                      href={`/profile/edit_profile/worker/${item.user_id}`}
                      className="w-100"
                    >
                      <button
                        type="button"
                        className={`btn ${styles["btn-purple"]} w-100`}
                      >
                        <p className={`${gStyle["open_sans_sb"]}`}>
                          Edit Profile
                        </p>
                      </button>
                    </Link>
                  </>
                ) : (
                  <></>
                )}
              </div>
              <div className={`ms-3 mb-5 skills-wrapper d-flex flex-column`}>
                <div className="title">
                  <p className={`${gStyle["open_sans_sb"]} h4`}>Skill</p>
                </div>
                <div className={`${styles["wrap-skill"]} row gap-2`}>
                  {props.dataSkill.length > 0 ? (
                    props.dataSkill.map((item, index) => (
                      <div key={index} className="skill-name col-5">
                        <button
                          type=""
                          className={`btn ${styles["btn-skill-custom"]} `}
                        >
                          <p className={`${styles["open_sans_sb h6"]}`}>
                            {item.name_skill}
                          </p>
                        </button>
                      </div>
                    ))
                  ) : (
                    <div>No data skill</div>
                  )}
                </div>
              </div>
              <div className="ms-3 mb-5 socmed-wrapper d-flex flex-column">
                <div className="mail-address-content d-flex gap-2">
                  <div className="mail-logo">
                    <i className="bi bi-envelope"></i>
                  </div>
                  <div className="mail-address">
                    <p className={`${styles["open_sans_lt"]} text-muted`}>
                      {item.email}
                    </p>
                  </div>
                </div>
                <div className="ig-content d-flex gap-2">
                  <div className="ig-logo">
                    <i className="bi bi-instagram"></i>
                  </div>
                  <div className="ig-name">
                    <p className={`${styles["open_sans_lt"]} text-muted`}>
                      {item.ig_account ? item.ig_account : <>No Data</>}
                    </p>
                  </div>
                </div>
                <div className="github-content d-flex gap-2">
                  <div className="github-logo">
                    <i className="bi bi-github"></i>
                  </div>
                  <div className="github-name">
                    <p className={`${styles["open_sans_lt"]} text-muted`}>
                      {item.git_account ? item.git_account : <>No Data</>}
                    </p>
                  </div>
                </div>
                <div className="tiktok-content d-flex gap-2">
                  <div className="tiktok-logo">
                    <i className="bi bi-git"></i>
                  </div>
                  <div className="mail-address">
                    <p className={`${styles["open_sans_lt"]} text-muted`}>
                      {item.gitlab_account ? item.gitlab_account : <>No Data</>}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={`position-absolute ${styles["card-aside-right"]}`}>
            <div className="ms-3 link-wrapper d-flex gap-5">
              <div className="mt-3 portofolio-Link">
                <button
                  className="btn"
                  type="button"
                  onClick={onPortofolio}
                  style={
                    showPortofolio
                      ? {
                          borderBottom: "3px solid #5E50A1",
                          background: "none",
                        }
                      : {}
                  }
                >
                  <p className={`${styles["open_sans_sb"]} h4 text-black`}>
                    Portofolio
                  </p>
                </button>
              </div>
              <div className="mt-3 portofolio-Link">
                <button
                  className="btn"
                  type="button"
                  onClick={onWorkExp}
                  style={
                    showWorkExp
                      ? {
                          borderBottom: "3px solid #5E50A1",
                          background: "none",
                        }
                      : {}
                  }
                >
                  <p className={`${styles["open_sans_sb"]} h4 text-black`}>
                    Pengalaman kerja
                  </p>
                </button>
              </div>
            </div>
            <div className="ms-3 mt-3 work-exp-wrapper">
              {showWorkExp ? <WorkExp user_id={id} /> : null}
            </div>
            <div className="ms-3 mt-3 kontent-wrapper">
              {showPortofolio ? <Portofolio user_id={id} /> : null}
            </div>
          </div>
        </div>
      ))}
    </>
  );
};

Index.layout = "L2";
export default Index;
