import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Auth.module.css'
import { useState } from 'react';
import { useRouter } from 'next/router';
import axios from "axios"


export default function Home() {
  const router = useRouter()

  const [form, setForm] = useState({
    email: '',
    password: '',
  })



  const onSubmitHandler = (e) => {
    e.preventDefault();
    if (form.email === '' || form.password === '') {
      alert('Please input your mail and password')
    } else {
      // console.log(form.email +""+ form.password)
      const body = {
        email: form.email,
        password: form.password
      };
      axios
        .post(`${process.env.APP_BACKEND_URL}/v1/user/login`, body)
        .then((response) => {
          console.log(response.data);
          if (!response.data.data) {
            alert('email atau password salah');
          } else {
            alert("login sukses");
            localStorage.setItem("token", response.data.data.token);
            localStorage.setItem("data", JSON.stringify(response.data.data.data));
            return (
              router.push('/landing')
            )
          }

        })
        .catch((err) => {
          if (err.response) {
            console.log(err.response.data);
            console.log(err.response.status);
            console.log(err.response.headers);
          } else if (err.request) {
            console.log(err.request);
          } else {
            console.log('Error', err.message);
          }
        })
    }
  }
  return (
    <div>
      <Head>
        <title>Login - HireJob</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div className={`row vw-100 vh-100 ${styles['bg-auth']}`}>
        <div className={`col-7 ${styles['col-xs-12']} col-sm-12 col-md-12 col-lg-7 col-xl-7 col-xxl-7 d-flex justify-content-center align-items-center`}>
          <div className={`w-75 h-75`}>
            <div className={`${styles['banner-auth']}`}>
              <div className='p-5'>
                <Link href='/landing'><Image src="/assets-img/white-logo.png" width={75} height={25} alt="wkwkw"></Image></Link>
              </div>
              <div className='h-75 w-100 d-flex align-items-center'>
                <p className={`p-5 display-5 ${styles['open_sans_sb']}`}>Temukan developer berbakat & terbaik di berbagai bidang keahlian</p>
              </div>
            </div>
          </div>
        </div>

        <div className={`col-5 ${styles['col-xs-12']} col-sm-12 col-md-12 col-lg-5 col-xl-5 col-xxl-5 d-flex justify-content-center align-items-center `}>
          <div className='w-75 '>
            <div className='title mb-5'>
              <p className={`h1 ${styles['open_sans_sb']}`}>Halo, Pewpeople</p>
              <p className={`h5 ${styles['open_sans_lt']}`}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In euismod ipsum et dio rhpmcis auctor.</p>
            </div>
            <div className='form'>
              <form onSubmit={(e) => onSubmitHandler(e)}>
                <div className="mb-3">
                  <label htmlFor="email" className={`form-label ${styles['open_sans_lt']}`} >Email</label>
                  <input type="email" className="form-control" id="email" aria-describedby="emailHelp" onChange={(e) => setForm({ ...form, email: e.target.value })} />
                </div>
                <div className="mb-3">
                  <label htmlFor="password" className={`form-label ${styles['open_sans_lt']}`}>Kata Sandi</label>
                  <input type="password" className="form-control" id="password" aria-describedby="emailHelp" onChange={(e) => setForm({ ...form, password: e.target.value })} />
                </div>
                <div className='text-end mb-2'>
                  <Link href="/reset_password/email_verify" className={`text-decoration-none  ${styles['open_sans_lt']} ${styles['hover-for-btn']}`}>Lupa kata sandi?</Link>
                </div>
                <div className='mb-3 button-submit w-100'>
                  <button className={`w-100 ${styles['btn-yellow']}`} type="submit">
                    <span className={`text-white ${styles['open_sans_sb']}`}>Masuk</span>
                  </button>
                </div>
                <div className='text-center'>
                  <p>Anda belum punya akun ? <span><Link href="/registers/register_choice" className={`text-decoration-none ${styles['txt-yellow-link']}`}>Daftar disini</Link></span></p>
                </div>

              </form>
            </div>

          </div>
        </div>
      </div>
    </div>
  )
}
